### ISSUE TITLE
ModuleNotFoundError: No module named 'gmail_main_sc'

### ISSUE THREAD

**Issue by nekromoff** [SokinjoNS/gmail-label-email-processor#1]
Thanks for the script, it would be helpful... but:

Your requirements are messed up (and...):
```
$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Invalid requirement: "'google-api-python-client>=2.88.0'," (from line 1 of requirements.txt)
```
I had to edit requirements and remove quotes and commas that are not supposed to be there. Each line must be just the packages:
```
google-api-python-client>=2.88.0
google-auth-httplib2>=0.1.0
google-auth-oauthlib>=1.0.0
gmail_api_auth==0.1.3
gmail_label_manager==0.1.3
gmail_message_processor==0.1.3
data_exporter==0.1.3
```

Output of launching your script:
```
$ gmail-processor
Traceback (most recent call last):
File "/XXXXXX/.local/bin/gmail-processor", line 5, in <module>
from gmail_main_sc import main
ModuleNotFoundError: No module named 'gmail_main_sc'
```

Tried to install locally:
```
pip install -e ./gmail-label-email-processor/
[...]
Installing collected packages: gmail-label-email-processor
Attempting uninstall: gmail-label-email-processor
Found existing installation: gmail-label-email-processor 1.0.3
Uninstalling gmail-label-email-processor-1.0.3:
Successfully uninstalled gmail-label-email-processor-1.0.3
Running setup.py develop for gmail-label-email-processor
Successfully installed gmail-label-email-processor
```

Still the same error:
```
$ gmail-processor
Traceback (most recent call last):
File "/XXX/.local/bin/gmail-processor", line 33, in <module>
sys.exit(load_entry_point('gmail-label-email-processor', 'console_scripts', 'gmail-processor')())
File "/XXX/.local/bin/gmail-processor", line 25, in importlib_load_entry_point
return next(matches).load()
File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
module = import_module(match.group('module'))
File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'gmail_main_sc'
```

**Comment by SokinjoNS** [comment]
Hi, tnx for reaching out. 
Will get it fixed as soon as I find some spare time. 
Tnx once again for letting me know. 
Cheers!

**Comment by nekromoff** [comment]
If you can point me where to find this module, I can send a pull request.
